version: "3.7"
services:
  timescale:
    image: timescale/timescaledb-postgis:latest-pg12
    container_name: timescale
    volumes:
      - "./timescale/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin123